name: xvega
channels:
  - conda-forge
dependencies:
# build dependencies
  - cmake
  - cxx-compiler
  - ninja
# host Dependencies
  - xvega=0.1.0
  - nlohmann_json=3.11.3
# Test dependencies
  - doctest

